#!/usr/bin/env bash

if [[ $1 == "delete" ]]; then
    docker stop poli-room-postgresql &> /dev/null || echo 'No container to stop...'
	docker rm poli-room-postgresql &> /dev/null || echo 'No container to remove...'
elif [[ $1 == "start" ]]; then
	docker start poli-room-postgresql
elif [[ $1 == "stop" ]]; then
	docker stop poli-room-postgresql &> /dev/null || echo 'No container to stop...'
elif [[ $1 == "setup" ]]; then
	docker stop poli-room-postgresql &> /dev/null || echo 'No container to stop...'
	docker rm poli-room-postgresql &> /dev/null || echo 'No container to remove...'
	echo "Creating new container now..."
	docker run --name poli-room-postgresql -p 5432:5432 -e POSTGRES_USER=poli-room -e POSTGRES_PASSWORD=poli-room -e POSTGRES_DB=poli-room -d postgres &> /dev/null;
	echo "Container created succesfully"
else
	echo "Choose one of the following options:"
	echo "delete  -> Remove any existing instances of the database"
	echo "start  -> Start a existing instance of the database, or create one if none exists"
	echo "stop -> Stop a running instance of the database"
	echo "setup -> Wipe and create a new database"
fi
